apiVersion: v1
kind: Secret
metadata:
  name: calcom
stringData:
  DATABASE_URL: postgresql://user:password@calcom-stack-postgresql/calcom
  NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000

  # It is highly recommended that the NEXTAUTH_SECRET must be overridden and very unique
  # Use `openssl rand -base64 32` to generate a key
  NEXTAUTH_SECRET: change_me

  # Encryption key that will be used to encrypt CalDAV credentials, choose a random string, for example with `dd if=/dev/urandom bs=1K count=1 | md5sum`
  CALENDSO_ENCRYPTION_KEY: change_me 
